### ISSUE TITLE
unable to read setup.py file

### ISSUE THREAD

**Issue by yinde0** [h2oai/pystacknet#8]
while installing i tried !sudo apt-get install pystacknet/setup.py on colab and python pystacknet/setup.py install on my desktop but got : 
Reading package lists... Done
''''''Building dependency tree       
Reading state information... Done
E: Unable to locate package setup.py
E: Couldn't find any package by glob 'setup.py'
E: Couldn't find any package by regex 'setup.py''''' on colab and
The main error
''''Traceback (most recent call last):
  File "pystacknet/setup.py", line 24, in <module>
    long_description=read_md('README.md'),
  File "pystacknet/setup.py", line 5, in <lambda>
    read_md = lambda f: convert(f, 'rst')
  File "/usr/local/lib/python3.6/dist-packages/pypandoc/__init__.py", line 66, in convert
    raise RuntimeError("Format missing, but need one (identified source as text as no "
RuntimeError: Format missing, but need one (identified source as text as no file with that name was found)''''

**Comment by atyamsriharsha** [comment]
Hey, @yinde0 the setup.py is not in the pystacknet folder.It is at the same level of pystacknet and the error shows the same saying that it could not locate the package setup.py
